language: python
before_install:
    - sudo pip install codecov
install:
    - sudo apt-get install pypy
    - pip install tox
    - pip install cffi
before_script:
    - ulimit -c unlimited -S
script:
    - python setup.py install
    - tox
after_success:
    codecov
env:
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
  - TOXENV=pypy3
