package:
  name: pycld2
  version: 0.42

source:
  - path: ..

build:
  number: 1

requirements:
  host:
    - python

  build:
    - {{ compiler('cxx') }}

test:
  requires:
    - python

  source_files:
    - test_pycld2.py

  commands:
    - python test_pycld2.py -v

about:
  home: https://github.com/aboSamoor/pycld2
  license: Apache Software License
  summary: Python bindings around Google Chromium's embedded compact language detection library (CLD2)
